In [2]:
import pandas as pd

In [3]:
retail=pd.read_csv(r'C:\Users\USUARIO\Documents\Projectos DS_practica\data-analysis-business\customer_shopping_behavior.csv')
retail

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
retail.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
retail.columns=retail.columns.str.lower()
retail.columns=retail.columns.str.replace(" ","_" )
retail=retail.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [7]:
retail['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [8]:
#Column for frecuency of purchases in days

frequency={'Every 3 Months': 90,
           'Annually': 365,
           'Quarterly': 90,
           'Monthly': 30,
           'Bi-Weekly': 14,
           'Fortnightly': 14,
           'Weekly': 7}
retail['frequency_of_purchases_days']= retail['frequency_of_purchases'].map(frequency)
retail[['frequency_of_purchases_days','frequency_of_purchases']]

      frequency_of_purchases_days frequency_of_purchases
0                              14            Fortnightly
1                              14            Fortnightly
2                               7                 Weekly
3                               7                 Weekly
4                             365               Annually
...                           ...                    ...
3895                            7                 Weekly
3896                           14              Bi-Weekly
3897                           90              Quarterly
3898                            7                 Weekly
3899                           90              Quarterly

[3900 rows x 2 columns]

In [9]:
#create a age group column
group=['Young Adult', "Adult", "Mid-aged", "Senior"]
retail['age_group']= pd.qcut(retail['age'], q=4, labels=group)
retail[['age_group', 'age']]

        age_group  age
0        Mid-aged   55
1     Young Adult   19
2        Mid-aged   50
3     Young Adult   21
4        Mid-aged   45
...           ...  ...
3895        Adult   40
3896     Mid-aged   52
3897     Mid-aged   46
3898        Adult   44
3899     Mid-aged   52

[3900 rows x 2 columns]

In [10]:
#confirm columns similiar
(retail['discount_applied']==retail['promo_code_used']).all()

np.True_

In [11]:
retail=retail.drop(columns='promo_code_used')

In [12]:
retail.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'frequency_of_purchases_days', 'age_group'],
      dtype='object')

In [13]:
#handling missing values
'''median due to  be robust a outliers'''

retail['review_rating'] = retail['review_rating'].fillna(
    retail.groupby('category')['review_rating'].transform('median')
)
retail['review_rating'].isna().sum()

np.int64(0)

In [14]:
from sqlalchemy import create_engine

# 1. Conexión a PostgreSQL
engine = create_engine("postgresql://postgres:postgres@localhost:5432/retail_customer")

# 3. Enviar dataframe a PostgreSQL
retail.to_sql("retail", engine, if_exists="replace", index=False)
print("Datos cargados exitosamente en la tabla 'retail_customer'.")

Datos cargados exitosamente en la tabla 'retail_customer'.

In [16]:
retail.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,frequency_of_purchases_days,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,14,Mid-aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,14,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,7,Mid-aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,7,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,365,Mid-aged